# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 618f96f9bc998404cc76a2c3c06e2847fd2bb7ff4c0e4328b93e95dd35709ead3f56efdc5d39b054c8c9d8737a7e559e9432e8c40368581df358d4b92c8830bf

test:
  secret_key_base: b9c9fb4cfcdfd495769d00776576c117a8e80b291e1a86fc5e8d4a7f48c65c9019d88c4eb5d2574cddb8c8086b41cded40c9e0eae5fa4d1d16cd9978d1e8fc6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
